// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3NxS7FrVPFBRW27aoR4KVn9Vx2xOu8kE',
    appId: '1:1050188445507:web:76744b999b949ba9f721f6',
    messagingSenderId: '1050188445507',
    projectId: 'ts-todo-portfolio-cb8c3',
    authDomain: 'ts-todo-portfolio-cb8c3.firebaseapp.com',
    storageBucket: 'ts-todo-portfolio-cb8c3.appspot.com',
    measurementId: 'G-4ST6GETX87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkfYTW9i1XCS4gGvu9pDlxTRacR_M-2wY',
    appId: '1:1050188445507:android:2d5f62d8efb758ebf721f6',
    messagingSenderId: '1050188445507',
    projectId: 'ts-todo-portfolio-cb8c3',
    storageBucket: 'ts-todo-portfolio-cb8c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqzpngQ92M5QEotDjiY1LHLhbYRFlquVY',
    appId: '1:1050188445507:ios:d644af23035e638df721f6',
    messagingSenderId: '1050188445507',
    projectId: 'ts-todo-portfolio-cb8c3',
    storageBucket: 'ts-todo-portfolio-cb8c3.appspot.com',
    iosBundleId: 'com.example.tsTodoPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqzpngQ92M5QEotDjiY1LHLhbYRFlquVY',
    appId: '1:1050188445507:ios:d644af23035e638df721f6',
    messagingSenderId: '1050188445507',
    projectId: 'ts-todo-portfolio-cb8c3',
    storageBucket: 'ts-todo-portfolio-cb8c3.appspot.com',
    iosBundleId: 'com.example.tsTodoPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3NxS7FrVPFBRW27aoR4KVn9Vx2xOu8kE',
    appId: '1:1050188445507:web:90f999f53dfe6465f721f6',
    messagingSenderId: '1050188445507',
    projectId: 'ts-todo-portfolio-cb8c3',
    authDomain: 'ts-todo-portfolio-cb8c3.firebaseapp.com',
    storageBucket: 'ts-todo-portfolio-cb8c3.appspot.com',
    measurementId: 'G-JDJVM7R8G8',
  );
}
